"""add explanation to line items

Revision ID: 273a007d3dbf
Revises: 06e713bf5bc6
Create Date: 2026-07-30 16:07:16.894928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273a007d3dbf'
down_revision: Union[str, None] = '06e713bf5bc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_line_items', sa.Column('explanation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bill_line_items', 'explanation')
    # ### end Alembic commands ###
